# Generated by Django 5.2.17 on 2026-08-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reviewhierarchysyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsnapshot',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reviewsnapshot',
            name='week_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyrunselection',
            name='source',
            field=models.CharField(default='weekly_release', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='reviewsnapshot',
            constraint=models.UniqueConstraint(fields=('project_id', 'snapshot_type', 'week_start'), name='uq_review_snapshot_project_type_week'),
        ),
    ]
