# Generated by Django 5.2

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_repair_weekly_selection_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRiskAssessment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('record_id', models.CharField(max_length=64)),
                (
                    'manual_rating',
                    models.CharField(
                        choices=[
                            ('low', 'Low'),
                            ('medium', 'Medium'),
                            ('high', 'High'),
                        ],
                        max_length=10,
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'module',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='record_risk_assessments',
                        to='core.globalmodule',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='record_risk_assessments',
                        to='core.project',
                    ),
                ),
                (
                    'rated_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='record_risk_assessments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'record_risk_assessments',
                'indexes': [
                    models.Index(
                        fields=['project', 'module', 'updated_at'],
                        name='risk_project_module_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('project', 'record_id'),
                        name='uq_project_record_risk_assessment',
                    ),
                ],
            },
        ),
    ]
